name: EsLint files on PR - reviewdog

on:
  pull_request:
    branches:
      - "**"

jobs:
  eslint:
    name: reviewdog / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          version: 3.6
      - uses: actions/setup-node@v1.1.0
        with:
          version: 10.17.0
      - uses: actions/checkout@v1
      - name: directory
        run: node --version && yarn --version
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.REPO_SYNC_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "packages/"
